apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: pipelinerun-1
spec:
  pipelineRef:
    name: application-pipeline
  resources:
    - name: docker-source
      resourceRef:
        name: demo-repo
    - name: builtImage
      resourceRef:
          name: hello-codi
  params:
    - name: pathToYamlFile
      value: "deploy.yaml"
  serviceAccountName: service-account
