apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: demo-repo
  namespace: default
spec:
  type: git
  params:
    - name: url
      value: https://github.com/rafalparadowski/flaszka-tekton
    - name: revision
      value: master

